#!/bin/bash
cd $OPENSHIFT_REPO_DIR/wsgi/openshift
GEOGRAPHY_TABLES=`echo 'SHOW TABLES LIKE "geography_%";' | ./manage.py dbshell | wc -l`
if [ $GEOGRAPHY_TABLES -eq 0 ]; then
	echo "--- loading new database schema"
	./manage.py sqlall geography | ./manage.py dbshell
else
	echo "--- skipping loading new database schema"
fi
./manage.py migrate geography 0001
./manage.py derived_data
