#!/bin/bash
cd $OPENSHIFT_REPO_DIR/wsgi/openshift
./manage.py sqlcustom geography | ./manage.py dbshell
./manage.py migrate geography --delete-ghost-migrations --traceback
./manage.py derived_elo_data
rm -rf $OPENSHIFT_DATA_DIR/.django_cache
