#!/bin/bash
SELF=$0
SELF_DIR=`dirname $SELF`
if [ $GEOGRAPHY_WORKSPACE_DIR ]; then
	WORKSPACE_DIR=$GEOGRAPHY_WORKSPACE_DIR;
else
	WORKSPACE_DIR=$SELF_DIR/../..
fi

if [ $GEOGRAPHY_ON_PRODUCTION ]; then
. $WORKSPACE_DIR/main/manage.py send_reminder_email
fi
